import 'package:automatic_demonstration/features/home_screen/data/models/food_stall_model.dart';

final List<FoodStallModel> enFoodStalls = [
  FoodStallModel(
    id: 1,
    name: "Fresh and Fresh Seafood",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Sau No Fresh Seafood is a famous seafood restaurant on Vinh Khanh street with 2 branches, known by many customers for its quality fresh seafood...",
    latitude: 10.763697,
    longitude: 106.701733,
    triggerRadius: 20,
    audioUrl: "1_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 2,
    name: "Fresh Seafood Restaurant with Snails",
    address: "Đường Vĩnh Khánh,Phường 9,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Be Con is a familiar fresh seafood restaurant on Vinh Khanh Street, focusing on carefully selected snails and clams...",
    latitude: 10.763378,
    longitude: 106.702011,
    triggerRadius: 12,
    audioUrl: "2_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 3,
    name: "Hai Lu Seafood Restaurant",
    address: "Đường Vĩnh Khánh,Phường 9,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Hai Lu Seafood Restaurant is a fresh seafood restaurant with a variety of processed menu from grilled, steamed to stir-fried...",
    latitude: 10.763263,
    longitude: 106.70211,
    triggerRadius: 12,
    audioUrl: "3_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 4,
    name: "Ky Kim beef hotpot",
    address: "106B Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Ky Kim Beef Hotpot is a fresh beef hotpot restaurant chosen by many diners in Vinh Khanh street...",
    latitude: 10.761425,
    longitude: 106.702563,
    triggerRadius: 15,
    audioUrl: "4_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 5,
    name: "Snail Loan Restaurant",
    address: "129 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Loan Restaurant is a familiar sidewalk restaurant on Vinh Khanh Street, featuring a late opening time until morning...",
    latitude: 10.761269,
    longitude: 106.702652,
    triggerRadius: 12,
    audioUrl: "5_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 6,
    name: "Vandal Shop 825",
    address: "99 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Tam Loi 825 shop is a popular pub and casual drink in Vinh Khanh area...",
    latitude: 10.761145,
    longitude: 106.702901,
    triggerRadius: 10,
    audioUrl: "6_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 7,
    name: "Snail Hong Nhung Restaurant",
    address: "38 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Hong Nhung Restaurant is a long-standing restaurant on Vinh Khanh Street, known by many diners for delicious dishes...",
    latitude: 10.761099,
    longitude: 106.702956,
    triggerRadius: 8,
    audioUrl: "7_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 8,
    name: "Snail Oanh Restaurant",
    address: "534 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Oanh Restaurant is one of the most famous snacks – seafood restaurants on Vinh Khanh Food Street...",
    latitude: 10.760852,
    longitude: 106.703294,
    triggerRadius: 12,
    audioUrl: "8_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 9,
    name: "Snail Restaurant 662",
    address: "662 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Restaurant 662 specializes in serving fresh snails and grilled seafood, stir-fried in sidewalk style...",
    latitude: 10.760733,
    longitude: 106.703442,
    triggerRadius: 10,
    audioUrl: "9_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 10,
    name: "Vinh Khanh",
    address: "131 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Vinh Khanh Snail is a traditional restaurant known by many diners...",
    latitude: 10.760609,
    longitude: 106.703657,
    triggerRadius: 10,
    audioUrl: "10_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 11,
    name: "Goat Hotpot & Signature",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Go Toan Hotpot & Sign is a specialty goat hotpot restaurant chosen by many diners when visiting Vinh Khanh...",
    latitude: 10.760539,
    longitude: 106.703742,
    triggerRadius: 8,
    audioUrl: "11_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 12,
    name: "Amin Fish Hotpot",
    address: "333 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "A Min Fish Hotpot is a Western specialty fish hotpot, featuring signature dishes such as snakehead fish hotpot...",
    latitude: 10.760595,
    longitude: 106.70416,
    triggerRadius: 15,
    audioUrl: "12_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 13,
    name: "Chilli Grilled Hot Pot",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Chilli Grilled Hot Pot is a buffet grilled hot pot restaurant that is popular with young people in Vinh Khanh street...",
    latitude: 10.760621,
    longitude: 106.704276,
    triggerRadius: 10,
    audioUrl: "13_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 14,
    name: "Grilled Hot Pot 79,000 VND",
    address: "833 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "79,000 VND GRILLED MOMT Hotpot is a cheap grilled hotpot shop in the form of 79,000 VND/person (unlimited food)...",
    latitude: 10.760702,
    longitude: 106.704363,
    triggerRadius: 10,
    audioUrl: "14_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 15,
    name: "Snail Van Restaurant",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Van Restaurant is a typical sidewalk snail shop on Vinh Khanh Street, specializing in freshly stir-fried snail dishes...",
    latitude: 10.760668,
    longitude: 106.704418,
    triggerRadius: 8,
    audioUrl: "15_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 16,
    name: "An Quan Grilled Hotpot",
    address: "122/27 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "An Quan Grilled Hot Pot is a seafood grilled hot pot restaurant that is loved by many diners...",
    latitude: 10.760733,
    longitude: 106.704482,
    triggerRadius: 8,
    audioUrl: "16_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 17,
    name: "Vinh Khanh Night Snail",
    address: "474 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Vinh Khanh Night Snail is a restaurant specializing in late night meals, featuring snail dishes and fresh seafood...",
    latitude: 10.760781,
    longitude: 106.704571,
    triggerRadius: 10,
    audioUrl: "17_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 18,
    name: "Snail Bar",
    address: "232 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Tavern is a restaurant specializing in snails and fresh seafood, featuring stir-fried snail dishes...",
    latitude: 10.760911,
    longitude: 106.704759,
    triggerRadius: 10,
    audioUrl: "18_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 19,
    name: "Grilled Sea Fish Bar",
    address: "231B Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Grilled Sea Fish Shop specializes in serving freshly grilled sea fish with processing styles such as grilled salt and chili...",
    latitude: 10.760968,
    longitude: 106.70484,
    triggerRadius: 10,
    audioUrl: "19_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 20,
    name: "Roasted spring rolls with local specialties",
    address: "122/45 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Grilled spring rolls Homeland Specialty is a long-standing grilled spring rolls shop with more than 60 years of operation...",
    latitude: 10.760826,
    longitude: 106.70489,
    triggerRadius: 8,
    audioUrl: "20_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 21,
    name: "Snail Dust Bar",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Dust is a popular snail shop loved by many diners in Vinh Khanh Street...",
    latitude: 10.761205,
    longitude: 106.705879,
    triggerRadius: 15,
    audioUrl: "21_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 22,
    name: "Crispy Chicken Rice with Larder, Ms. Hai",
    address: "8/11 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Co Hai Fatty Chicken Rice is a famous rustic fattening chicken rice shop in Vinh Khanh culinary quarter...",
    latitude: 10.760946,
    longitude: 106.706322,
    triggerRadius: 12,
    audioUrl: "22_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 23,
    name: "Thai Sukiyaki hotpot",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Thai Sukiyaki Hotpot is a Thai-style hotpot shop with a typical spicy taste...",
    latitude: 10.760927,
    longitude: 106.706356,
    triggerRadius: 8,
    audioUrl: "23_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 24,
    name: "Snail Phat Quan",
    address: "46 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Phat Quan is a familiar street food and seafood restaurant on Vinh Khanh Street...",
    latitude: 10.760814,
    longitude: 106.706552,
    triggerRadius: 10,
    audioUrl: "24_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 25,
    name: "Thy Grilled Snakehead",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Thy Thy Grilled Snakehead Fish is a restaurant specializing in grilled snakehead fish – a rustic Western specialty...",
    latitude: 10.760836,
    longitude: 106.706579,
    triggerRadius: 6,
    audioUrl: "25_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 26,
    name: "Grill 79",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Grill 79 is a casual barbecue with a variety of sidewalk grill menus...",
    latitude: 10.760765,
    longitude: 106.706642,
    triggerRadius: 8,
    audioUrl: "26_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 27,
    name: "Grilled Ut",
    address: "24 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Ms. Ut Niet is a familiar seafood and meat grill on Vinh Khanh Street...",
    latitude: 10.760673,
    longitude: 106.70679,
    triggerRadius: 10,
    audioUrl: "27_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 28,
    name: "Grilled Pork Breast Advance",
    address: "89 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Tien Up Grilled Pork Breast is a bar specializing in crispy grilled pork breasts...",
    latitude: 10.76049,
    longitude: 106.707169,
    triggerRadius: 15,
    audioUrl: "28_en.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
];
