import 'package:automatic_demonstration/features/home_screen/data/models/food_stall_model.dart';

final List<FoodStallModel> jaFoodStalls = [
  FoodStallModel(
    id: 1,
    name: "フレッシュ＆フレッシュシーフード",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Sau No Fresh Seafoodは、 Vinh Khanh通りにある有名なシーフードレストランで、 2つの支店があり、質の高い新鮮なシーフードで多くの顧客に知られています...",
    latitude: 10.763697,
    longitude: 106.701733,
    triggerRadius: 20,
    audioUrl: "1_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 2,
    name: "新鮮なシーフードレストラン（カタツムリ付き）",
    address: "Đường Vĩnh Khánh,Phường 9,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Be ConはVinh Khanh通りにあるおなじみの新鮮なシーフードレストランで、厳選されたカタツムリとアサリを中心としています...",
    latitude: 10.763378,
    longitude: 106.702011,
    triggerRadius: 12,
    audioUrl: "2_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 3,
    name: "ハイルーシーフードレストラン",
    address: "Đường Vĩnh Khánh,Phường 9,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Hai Lu Seafood Restaurantは、焼き物、蒸し物、炒め物など、さまざまな加工メニューを取り揃えた新鮮なシーフードレストランです...",
    latitude: 10.763263,
    longitude: 106.70211,
    triggerRadius: 12,
    audioUrl: "3_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 4,
    name: "キキム牛肉鍋",
    address: "106B Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Ky Kim Beef Hotpotは、 Vinh Khanh通りで多くのダイナーに選ばれている新鮮な牛肉鍋レストランです...",
    latitude: 10.761425,
    longitude: 106.702563,
    triggerRadius: 15,
    audioUrl: "4_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 5,
    name: "カタツムリローンレストラン",
    address: "129 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Loan Restaurantは、 Vinh Khanh通りにあるなじみのある歩道レストランで、朝まで営業時間を遅らせているのが特徴です...",
    latitude: 10.761269,
    longitude: 106.702652,
    triggerRadius: 12,
    audioUrl: "5_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 6,
    name: "ヴァンダルショップ825",
    address: "99 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Tam Loi 825ショップは、 Vinh Khanhエリアで人気のパブ＆カジュアルドリンクです...",
    latitude: 10.761145,
    longitude: 106.702901,
    triggerRadius: 10,
    audioUrl: "6_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 7,
    name: "カタツムリホンニュンレストラン",
    address: "38 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Hong Nhung Restaurantは、 Vinh Khanh通りにある老舗レストランで、多くのお食事に美味しい料理で知られています...",
    latitude: 10.761099,
    longitude: 106.702956,
    triggerRadius: 8,
    audioUrl: "7_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 8,
    name: "カタツムリオアンレストラン",
    address: "534 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Oanh Restaurantは、 Vinh Khanhフードストリートで最も有名なスナック・シーフードレストランの1つです...",
    latitude: 10.760852,
    longitude: 106.703294,
    triggerRadius: 12,
    audioUrl: "8_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 9,
    name: "カタツムリレストラン662",
    address: "662 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "カタツムリハウス662は、新鮮なカタツムリと焼きシーフードを専門とし、歩道スタイルで炒めています...",
    latitude: 10.760733,
    longitude: 106.703442,
    triggerRadius: 10,
    audioUrl: "9_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 10,
    name: "ビン・カーン",
    address: "131 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Vinh Khanh Snailは、多くのお食事に知られる伝統的なレストランです...",
    latitude: 10.760609,
    longitude: 106.703657,
    triggerRadius: 10,
    audioUrl: "10_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 11,
    name: "ヤギの鍋と看板",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Go Toan Hotpot & Signは、 Vinh Khanhを訪れる際に多くのお食事に選ばれる名物のヤギ鍋レストランです...",
    latitude: 10.760539,
    longitude: 106.703742,
    triggerRadius: 8,
    audioUrl: "11_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 12,
    name: "アミン魚鍋",
    address: "333 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "A Min Fish Hotpotは、スネークヘッドの魚の鍋などの代表的な料理を特徴とする、西洋名物の魚の鍋です...",
    latitude: 10.760595,
    longitude: 106.70416,
    triggerRadius: 15,
    audioUrl: "12_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 13,
    name: "唐辛子焼き鍋",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Chilli Grilled Hot Potは、 Vinh Khanh通りの若者に人気のビュッフェ式焼き鍋レストランです...",
    latitude: 10.760621,
    longitude: 106.704276,
    triggerRadius: 10,
    audioUrl: "13_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 14,
    name: "焼き鍋79,000 VND",
    address: "833 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "79,000 VND GRILLED MOMT Hotpotは、 79,000 VND/人（食べ放題）の格安焼き鍋店です...",
    latitude: 10.760702,
    longitude: 106.704363,
    triggerRadius: 10,
    audioUrl: "14_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 15,
    name: "カタツムリバンレストラン",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "カタツムリトラックの家15 (Snail Van Restaurant) は、 Vinh Khanh通りの典型的な道端のカタツムリショップで、 出来たての炒めカタツムリ料理を専門としています...",
    latitude: 10.760668,
    longitude: 106.704418,
    triggerRadius: 8,
    audioUrl: "15_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 16,
    name: "安慶焼き鍋",
    address: "122/27 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "An Quan Grilled Hot Potは、多くのダイナーに愛されているシーフードグリル鍋レストランです...",
    latitude: 10.760733,
    longitude: 106.704482,
    triggerRadius: 8,
    audioUrl: "16_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 17,
    name: "ビン・カーン・ナイト・スネール",
    address: "474 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Vinh Khanh Night Snailは、深夜の食事を専門とするレストランで、カタツムリ料理と新鮮なシーフードを楽しめます...",
    latitude: 10.760781,
    longitude: 106.704571,
    triggerRadius: 10,
    audioUrl: "17_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 18,
    name: "カタツムリバー",
    address: "232 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Tavernはカタツムリと新鮮なシーフードを専門とするレストランで、炒めカタツムリ料理が特徴です...",
    latitude: 10.760911,
    longitude: 106.704759,
    triggerRadius: 10,
    audioUrl: "18_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 19,
    name: "焼き海魚バー",
    address: "231B Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "焼き魚専門店は、塩焼きや唐辛子焼きなどの加工スタイルで、焼きたての海水魚を専門としています...",
    latitude: 10.760968,
    longitude: 106.70484,
    triggerRadius: 10,
    audioUrl: "19_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 20,
    name: "地元の特産品を添えた焼き春巻き",
    address: "122/45 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "GRILLED SPRING ROLLS HOMELAND SPECIALTYは、 60年以上の歴史を持つ老舗の焼き春巻きショップです...",
    latitude: 10.760826,
    longitude: 106.70489,
    triggerRadius: 8,
    audioUrl: "20_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 21,
    name: "スネールダストバー",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Dustは、 Vinh Khanh通りの多くのダイナーに愛されている人気のカタツムリショップです...",
    latitude: 10.761205,
    longitude: 106.705879,
    triggerRadius: 15,
    audioUrl: "21_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 22,
    name: "ラーダーを添えたカリカリチキンライス、ハイさん",
    address: "8/11 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Co Hai Fatty Chicken Riceは、 Vinh Khanh料理地区にある有名な素朴な肥育チキンライスショップです...",
    latitude: 10.760946,
    longitude: 106.706322,
    triggerRadius: 12,
    audioUrl: "22_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 23,
    name: "タイ・スキヤキ鍋",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Thai Sukiyaki Hotpotは、独特の辛みを持つタイ風鍋店です...",
    latitude: 10.760927,
    longitude: 106.706356,
    triggerRadius: 8,
    audioUrl: "23_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 24,
    name: "カタツムリファット・クアン",
    address: "46 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Phat Quanは、 Vinh Khanh通りにあるなじみのある屋台の食べ物とシーフードのレストランです...",
    latitude: 10.760814,
    longitude: 106.706552,
    triggerRadius: 10,
    audioUrl: "24_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 25,
    name: "君主の焼き雷魚",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Thy Thy Grilled Snakehead Fishは、素朴な西洋料理である焼き雷魚を専門とするレストランです...",
    latitude: 10.760836,
    longitude: 106.706579,
    triggerRadius: 6,
    audioUrl: "25_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 26,
    name: "グリル79",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "グリル79は、歩道のグリルメニューを豊富に取り揃えたカジュアルなバーベキューです...",
    latitude: 10.760765,
    longitude: 106.706642,
    triggerRadius: 8,
    audioUrl: "26_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 27,
    name: "焼き食べ",
    address: "24 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Ut Nietさんは、 Vinh Khanh通りにあるなじみのあるシーフードと肉のグリルです...",
    latitude: 10.760673,
    longitude: 106.70679,
    triggerRadius: 10,
    audioUrl: "27_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 28,
    name: "焼き豚胸肉アドバンス",
    address: "89 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Tien Up Grilled Pork Breastは、カリカリの豚胸肉グリルを専門とするバーです...",
    latitude: 10.76049,
    longitude: 106.707169,
    triggerRadius: 15,
    audioUrl: "28_ja.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
];
