import 'package:automatic_demonstration/features/home_screen/data/models/food_stall_model.dart';

final List<FoodStallModel> koFoodStalls = [
  FoodStallModel(
    id: 1,
    name: "신선하고 신선한 해산물",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Sau No Fresh Seafood는 빈칸거리에 위치한 유명한 해산물 레스토랑으로 2개의 지점이 있으며 고품질의 신선한 해산물로 많은 고객들에게 알려져 있습니다...",
    latitude: 10.763697,
    longitude: 106.701733,
    triggerRadius: 20,
    audioUrl: "1_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 2,
    name: "신선한 해산물 레스토랑 (달팽이 포함)",
    address: "Đường Vĩnh Khánh,Phường 9,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Be Con은 빈칸 거리에 있는 친숙한 신선한 해산물 레스토랑으로 엄선된 달팽이와 조개에 중점을 둡니다...",
    latitude: 10.763378,
    longitude: 106.702011,
    triggerRadius: 12,
    audioUrl: "2_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 3,
    name: "하이루 해산물 레스토랑",
    address: "Đường Vĩnh Khánh,Phường 9,Quận 4,Thành Phố Hồ Chí Minh",
    description: "하이루 해산물 레스토랑은 구이, 찜, 볶음 등 다양한 가공 메뉴를 갖춘 신선한 해산물 레스토랑입니다...",
    latitude: 10.763263,
    longitude: 106.70211,
    triggerRadius: 12,
    audioUrl: "3_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 4,
    name: "귀김 쇠고기 훠궈",
    address: "106B Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Ky Kim Beef Hotpot은 빈칸거리(Vinh Khanh street)의 많은 식객들이 선택하는 신선한 소고기 전골 레스토랑입니다...",
    latitude: 10.761425,
    longitude: 106.702563,
    triggerRadius: 15,
    audioUrl: "4_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 5,
    name: "스네일 론 레스토랑",
    address: "129 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Loan 레스토랑은 빈칸 거리(Vinh Khanh Street)에 있는 친숙한 인도변 레스토랑으로 아침까지 늦게 영업하는 것이 특징입니다...",
    latitude: 10.761269,
    longitude: 106.702652,
    triggerRadius: 12,
    audioUrl: "5_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 6,
    name: "반달 숍 825",
    address: "99 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Tam Loi 825 샵은 빈칸(Vinh Khanh) 지역의 인기 펍 겸 캐주얼 음료입니다...",
    latitude: 10.761145,
    longitude: 106.702901,
    triggerRadius: 10,
    audioUrl: "6_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 7,
    name: "스네일 홍능 레스토랑",
    address: "38 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Hong Nhung 레스토랑은 빈칸 거리(Vinh Khanh Street)에 있는 유서 깊은 레스토랑으로 많은 식객들에게 맛있는 요리로 알려져 있습니다...",
    latitude: 10.761099,
    longitude: 106.702956,
    triggerRadius: 8,
    audioUrl: "7_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 8,
    name: "스네일 안 레스토랑",
    address: "534 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "스네일 안 레스토랑은 빈칸 맛집 거리(Vinh Khanh Food Street)에서 가장 유명한 스낵 - 해산물 레스토랑 중 하나입니다...",
    latitude: 10.760852,
    longitude: 106.703294,
    triggerRadius: 12,
    audioUrl: "8_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 9,
    name: "스네일 레스토랑 662",
    address: "662 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "달팽이집 662는 신선한 달팽이와 구운 해산물을 전문으로 하며 노점식으로 볶아냅니다...",
    latitude: 10.760733,
    longitude: 106.703442,
    triggerRadius: 10,
    audioUrl: "9_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 10,
    name: "빈칸",
    address: "131 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Vinh Khanh Snail은 많은 식객들에게 알려진 전통 레스토랑입니다...",
    latitude: 10.760609,
    longitude: 106.703657,
    triggerRadius: 10,
    audioUrl: "10_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 11,
    name: "염소 전골 및 시그니처",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Go Toan Hotpot & Sign은 빈칸(Vinh Khanh) 방문 시 많은 식객들이 선택하는 특제 염소 전골 레스토랑입니다...",
    latitude: 10.760539,
    longitude: 106.703742,
    triggerRadius: 8,
    audioUrl: "11_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 12,
    name: "아민 피쉬 훠궈",
    address: "333 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "A Min Fish Hotpot은 가물치 전골 등 시그니처 요리를 선보이는 서양식 특제 생선 전골입니다...",
    latitude: 10.760595,
    longitude: 106.70416,
    triggerRadius: 15,
    audioUrl: "12_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 13,
    name: "칠리 그릴 전골",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "칠리 그릴드 핫팟(Chilli Grilled Hot Pot)은 빈칸 거리(Vinh Khanh street)의 젊은이들에게 인기 있는 뷔페식 구이 전골 레스토랑입니다...",
    latitude: 10.760621,
    longitude: 106.704276,
    triggerRadius: 10,
    audioUrl: "13_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 14,
    name: "79,000VND 그릴 전골",
    address: "833 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "79,000 VND GRILLED MOMT 전골은 79,000 VND/인(음식 무제한) 형태의 저렴한 구이 전골 가게입니다...",
    latitude: 10.760702,
    longitude: 106.704363,
    triggerRadius: 10,
    audioUrl: "14_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 15,
    name: "스네일 밴 레스토랑",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "달팽이 트럭집 15(Snail Van Restaurant)는 빈칸 거리(Vinh Khanh Street)의 전형적인 길거리 달팽이 가게로 갓 볶은 달팽이 요리를 전문으로 합니다...",
    latitude: 10.760668,
    longitude: 106.704418,
    triggerRadius: 8,
    audioUrl: "15_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 16,
    name: "안콴 구이 전골",
    address: "122/27 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "안콴 구이전골(An Quan Grilled Hot Pot)은 많은 미식가들에게 사랑받는 해산물 구이전골 레스토랑입니다...",
    latitude: 10.760733,
    longitude: 106.704482,
    triggerRadius: 8,
    audioUrl: "16_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 17,
    name: "빈칸 나이트 스네일",
    address: "474 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "빈칸 야밤 골뱅이(Vinh Khanh Night Snail)는 달팽이 요리와 신선한 해산물을 갖춘 심야 식사 전문 레스토랑입니다...",
    latitude: 10.760781,
    longitude: 106.704571,
    triggerRadius: 10,
    audioUrl: "17_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 18,
    name: "스네일 바",
    address: "232 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Tavern은 달팽이와 신선한 해산물을 전문으로 하는 레스토랑으로 볶은 달팽이 요리가 특징입니다...",
    latitude: 10.760911,
    longitude: 106.704759,
    triggerRadius: 10,
    audioUrl: "18_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 19,
    name: "구운 바다 생선 바",
    address: "231B Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "구운 생선 전문점은 소금과 고추를 곁들인 구이와 같은 가공 스타일로 갓 구운 바다 생선을 전문으로 합니다...",
    latitude: 10.760968,
    longitude: 106.70484,
    triggerRadius: 10,
    audioUrl: "19_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 20,
    name: "지역 특산물을 곁들인 구운 튀김",
    address: "122/45 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "GRILLED SPRING ROLLS HOMELAND SPECIALTY는 60년 이상의 역사를 자랑하는 유서 깊은 구운 스프링 롤 샵입니다...",
    latitude: 10.760826,
    longitude: 106.70489,
    triggerRadius: 8,
    audioUrl: "20_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 21,
    name: "스네일 더스트 바",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "달팽이 더스트(Snail Dust)는 빈칸 거리(Vinh Khanh Street)에서 많은 미식가들에게 사랑받는 인기 달팽이 가게입니다...",
    latitude: 10.761205,
    longitude: 106.705879,
    triggerRadius: 15,
    audioUrl: "21_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 22,
    name: "라더를 곁들인 바삭한 치킨 라이스, 하이 양",
    address: "8/11 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Co Hai Fatty Chicken Rice는 빈칸(Vinh Khanh) 요리 구역에서 유명한 소박한 살찌는 치킨 라이스 가게입니다...",
    latitude: 10.760946,
    longitude: 106.706322,
    triggerRadius: 12,
    audioUrl: "22_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 23,
    name: "태국식 수키야키 전골",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Thai Sukiyaki Hotpot은 전형적인 매운맛을 지닌 태국식 전골 가게입니다...",
    latitude: 10.760927,
    longitude: 106.706356,
    triggerRadius: 8,
    audioUrl: "23_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 24,
    name: "스네일 파트 콴",
    address: "46 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Phat Quan은 빈칸 거리(Vinh Khanh Street)에 있는 친숙한 거리 음식 및 해산물 레스토랑입니다...",
    latitude: 10.760814,
    longitude: 106.706552,
    triggerRadius: 10,
    audioUrl: "24_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 25,
    name: "Thy 구운 가물치",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Thy Thy Grilled Snakehead Fish는 서양식 시골 요리인 구운 가물치를 전문으로 하는 레스토랑입니다...",
    latitude: 10.760836,
    longitude: 106.706579,
    triggerRadius: 6,
    audioUrl: "25_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 26,
    name: "그릴 79",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "그릴 79(Grill 79)는 다양한 노점 그릴 메뉴를 갖춘 캐주얼 바비큐입니다...",
    latitude: 10.760765,
    longitude: 106.706642,
    triggerRadius: 8,
    audioUrl: "26_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 27,
    name: "구운 먹기",
    address: "24 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Ut Niet 씨는 빈칸 거리(Vinh Khanh Street)에 있는 친숙한 해산물 및 육류 구이 식당입니다...",
    latitude: 10.760673,
    longitude: 106.70679,
    triggerRadius: 10,
    audioUrl: "27_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 28,
    name: "구운 돼지 가슴살 어드밴스",
    address: "89 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Tien Up Grilled Pork Breast는 바삭한 돼지 가슴살 구이 전문 바입니다...",
    latitude: 10.76049,
    longitude: 106.707169,
    triggerRadius: 15,
    audioUrl: "28_ko.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
];
