import 'package:automatic_demonstration/features/home_screen/data/models/food_stall_model.dart';

final List<FoodStallModel> zhFoodStalls = [
  FoodStallModel(
    id: 1,
    name: "新鲜海鲜",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Sau No Fresh Seafood是一家著名的海鲜餐厅，位于永庆街（ Vinh Khanh street ） ，有2家分店，以其优质的新鲜海鲜而闻名...",
    latitude: 10.763697,
    longitude: 106.701733,
    triggerRadius: 20,
    audioUrl: "1_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 2,
    name: "新鲜海鲜餐厅（含蜗牛）",
    address: "Đường Vĩnh Khánh,Phường 9,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Be Con是永庆街上一家熟悉的新鲜海鲜餐厅，专注于精心挑选的蜗牛和蛤蜊...",
    latitude: 10.763378,
    longitude: 106.702011,
    triggerRadius: 12,
    audioUrl: "2_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 3,
    name: "海路海鲜餐厅",
    address: "Đường Vĩnh Khánh,Phường 9,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Hai Lu Seafood Restaurant是一家新鲜的海鲜餐厅，提供从烤、蒸到炒的各种加工菜单...",
    latitude: 10.763263,
    longitude: 106.70211,
    triggerRadius: 12,
    audioUrl: "3_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 4,
    name: "Ky Kim牛肉火锅",
    address: "106B Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Ky Kim Beef Hotpot是永庆街（ Vinh Khanh street ）许多食客选择的新鲜牛肉火锅餐厅...",
    latitude: 10.761425,
    longitude: 106.702563,
    triggerRadius: 15,
    audioUrl: "4_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 5,
    name: "Snail Loan Restaurant",
    address: "129 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "蜗牛贷款餐厅（ Snail Loan Restaurant ）是永庆街（ Vinh Khanh Street ）上一家熟悉的人行道餐厅，营业时间延迟至早晨...",
    latitude: 10.761269,
    longitude: 106.702652,
    triggerRadius: 12,
    audioUrl: "5_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 6,
    name: "Vandal Shop 825",
    address: "99 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Tam Loi 825商店是永庆（ Vinh Khanh ）地区的热门酒吧 and 休闲饮品...",
    latitude: 10.761145,
    longitude: 106.702901,
    triggerRadius: 10,
    audioUrl: "6_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 7,
    name: "Snail Hong Nhung餐厅",
    address: "38 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Hong Nhung餐厅是永庆街（ Vinh Khanh Street ）上一家历史悠久的餐厅，许多食客都以美味佳肴而闻名……",
    latitude: 10.761099,
    longitude: 106.702956,
    triggerRadius: 8,
    audioUrl: "7_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 8,
    name: "Snail Oanh餐厅",
    address: "534 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Oanh餐厅是永庆美食街（ Vinh Khanh Food Street ）上最著名的海鲜餐厅之一……",
    latitude: 10.760852,
    longitude: 106.703294,
    triggerRadius: 12,
    audioUrl: "8_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 9,
    name: "Snail Restaurant 662",
    address: "662 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Restaurant 662专门供应新鲜的蜗牛 and 烤海鲜，以人行道风格炒制...",
    latitude: 10.760733,
    longitude: 106.703442,
    triggerRadius: 10,
    audioUrl: "9_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 10,
    name: "永庆",
    address: "131 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "永庆蜗牛（ Vinh Khanh Snail ）是一家众所周知的传统餐厅……",
    latitude: 10.760609,
    longitude: 106.703657,
    triggerRadius: 10,
    audioUrl: "10_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 11,
    name: "山羊火锅 and 招牌",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Go Toan Hotpot & Sign是许多食客在参观永庆（ Vinh Khanh ）时选择的特色山羊火锅餐厅...",
    latitude: 10.760539,
    longitude: 106.703742,
    triggerRadius: 8,
    audioUrl: "11_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 12,
    name: "阿明鱼火锅",
    address: "333 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "闽鱼火锅是一种西式特色鱼火锅，以蛇头鱼火锅等招牌菜肴为特色...",
    latitude: 10.760595,
    longitude: 106.70416,
    triggerRadius: 15,
    audioUrl: "12_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 13,
    name: "辣椒烤火锅",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "辣椒烤火锅（ Chilli Grilled Hot Pot ）是一家自助烤火锅餐厅，深受永庆街（ Vinh Khanh street ）年轻人的喜爱...",
    latitude: 10.760621,
    longitude: 106.704276,
    triggerRadius: 10,
    audioUrl: "13_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 14,
    name: "烤火锅79,000越南盾",
    address: "833 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "79,000越南盾烧烤Momt火锅是一家便宜的烧烤火锅店，价格为79,000越南盾/人（无限量食品）...",
    latitude: 10.760702,
    longitude: 106.704363,
    triggerRadius: 10,
    audioUrl: "14_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 15,
    name: "Snail Van Restaurant",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "蜗牛面包车餐厅（ Snail Van Restaurant ）是永庆街（ Vinh Khanh Street ）上一家典型的人行道蜗牛店，专门供应新鲜炒蜗牛菜肴...",
    latitude: 10.760668,
    longitude: 106.704418,
    triggerRadius: 8,
    audioUrl: "15_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 16,
    name: "全烤火锅",
    address: "122/27 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Quan Grilled Hot Pot是一家海鲜烤火锅餐厅，深受众多食客的喜爱...",
    latitude: 10.760733,
    longitude: 106.704482,
    triggerRadius: 8,
    audioUrl: "16_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 17,
    name: "永庆夜蜗牛之旅",
    address: "474 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "永庆夜蜗牛（ Vinh Khanh Night Snail ）是一家专门提供深夜美食的餐厅，提供蜗牛菜肴 and 新鲜海鲜......",
    latitude: 10.760781,
    longitude: 106.704571,
    triggerRadius: 10,
    audioUrl: "17_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 18,
    name: "蜗牛吧",
    address: "232 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Tavern是一家专门供应蜗牛 and 新鲜海鲜的餐厅，提供炒蜗牛菜肴...",
    latitude: 10.760911,
    longitude: 106.704759,
    triggerRadius: 10,
    audioUrl: "18_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 19,
    name: "烤海鱼吧",
    address: "231B Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "烤海鱼店专门供应新鲜烤海鱼，具有烤盐 and 辣椒等加工风格……",
    latitude: 10.760968,
    longitude: 106.70484,
    triggerRadius: 10,
    audioUrl: "19_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 20,
    name: "烤春卷配当地特色菜",
    address: "122/45 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "GRILLED SPRING ROLLS HOMELAND SPECIALTY是一家拥有60多年历史的GRILLED SPRING ROLLS SHOP...",
    latitude: 10.760826,
    longitude: 106.70489,
    triggerRadius: 8,
    audioUrl: "20_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 21,
    name: "Snail Dust Bar",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Dust是永庆街（ Vinh Khanh Street ）众多食客喜爱的热门蜗牛店……",
    latitude: 10.761205,
    longitude: 106.705879,
    triggerRadius: 15,
    audioUrl: "21_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 22,
    name: "酥脆鸡饭搭配拉德尔，海女士",
    address: "8/11 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Co Hai Fatty Chicken Rice是永庆（ Vinh Khanh ）烹饪区著名的乡村育肥鸡饭店...",
    latitude: 10.760946,
    longitude: 106.706322,
    triggerRadius: 12,
    audioUrl: "22_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 23,
    name: "泰式烧烤火锅",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Thai Sukiyaki Hotpot是一家泰式火锅店，有着典型的辛辣口味……",
    latitude: 10.760927,
    longitude: 106.706356,
    triggerRadius: 8,
    audioUrl: "23_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 24,
    name: "Snail Phat Quan",
    address: "46 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Snail Phat Quan是永庆街（ Vinh Khanh Street ）上一家熟悉的街头美食 and 海鲜餐厅...",
    latitude: 10.760814,
    longitude: 106.706552,
    triggerRadius: 10,
    audioUrl: "24_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 25,
    name: "Thy烤蛇头",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Thy Thy Grilled Snakehead Fish是一家专门提供烤蛇头鱼的餐厅，这是一种质朴的西式特色菜......",
    latitude: 10.760836,
    longitude: 106.706579,
    triggerRadius: 6,
    audioUrl: "25_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 26,
    name: "烤架79",
    address: "Đường Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Grill 79是一种休闲烧烤，提供各种人行道烧烤菜单......",
    latitude: 10.760765,
    longitude: 106.706642,
    triggerRadius: 8,
    audioUrl: "26_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 27,
    name: "Grilled Ut",
    address: "24 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Ut Niet女士是永庆街（ Vinh Khanh Street ）上熟悉的海鲜 and 肉类烧烤店...",
    latitude: 10.760673,
    longitude: 106.70679,
    triggerRadius: 10,
    audioUrl: "27_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
  FoodStallModel(
    id: 28,
    name: "烤猪胸肉提前",
    address: "89 Vĩnh Khánh,Phường 8,Quận 4,Thành Phố Hồ Chí Minh",
    description: "Tien Up Grilled Pork Breast是一家专门提供酥脆烤猪胸肉的酒吧...",
    latitude: 10.76049,
    longitude: 106.707169,
    triggerRadius: 15,
    audioUrl: "28_zh.mp3",
    imageUrl: '',
    minPrice: 30000,
    maxPrice: 150000,
    audioDuration: 120,
    featuredReview: ["Good food", "Nice place"],
    rating: 0.0,
  ),
];
